<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\TicketU;
use App\Models\User;

class TicketSeeder extends Seeder
{
    public function run(): void
    {
        // Usuarios que NO pertenecen a Tecnologías
        $usuarios = User::where('departamento_id', '!=', 2)->get();

        if ($usuarios->isEmpty()) {
            $this->command->error('No hay usuarios disponibles para crear tickets.');
            return;
        }

        $tickets = [
            [
                'titulo' => 'La computadora no enciende',
                'tipo_falla' => 'Hardware',
                'equipo' => 'PC de escritorio',
                'prioridad' => 'Critica',
                'descripcion' => 'La computadora no enciende al presionar el botón de encendido.',
                'afecta_otros' => false,
                'es_recurrente' => false,
                'comentarios' => null,
                'evidencia' => null,
                'informacion_adicional' => null,
            ],
            [
                'titulo' => 'Internet lento',
                'tipo_falla' => 'Red',
                'equipo' => 'Laptop',
                'prioridad' => 'Alta',
                'descripcion' => 'La conexión a Internet está demasiado lenta durante toda la jornada.',
                'afecta_otros' => true,
                'es_recurrente' => true,
                'comentarios' => null,
                'evidencia' => null,
                'informacion_adicional' => null,
            ],
            [
                'titulo' => 'No puedo imprimir',
                'tipo_falla' => 'Impresora',
                'equipo' => 'Impresora HP',
                'prioridad' => 'Media',
                'descripcion' => 'La impresora no responde al enviar documentos.',
                'afecta_otros' => true,
                'es_recurrente' => false,
                'comentarios' => null,
                'evidencia' => null,
                'informacion_adicional' => null,
            ],
            [
                'titulo' => 'Error al iniciar sesión',
                'tipo_falla' => 'Software',
                'equipo' => 'Laptop',
                'prioridad' => 'Alta',
                'descripcion' => 'El sistema muestra un error al intentar iniciar sesión.',
                'afecta_otros' => false,
                'es_recurrente' => false,
                'comentarios' => null,
                'evidencia' => null,
                'informacion_adicional' => null,
            ],
            [
                'titulo' => 'Monitor sin señal',
                'tipo_falla' => 'Hardware',
                'equipo' => 'Monitor Dell',
                'prioridad' => 'Media',
                'descripcion' => 'El monitor muestra el mensaje de que no existe señal.',
                'afecta_otros' => false,
                'es_recurrente' => false,
                'comentarios' => null,
                'evidencia' => null,
                'informacion_adicional' => null,
            ],
            [
                'titulo' => 'Teclado no funciona',
                'tipo_falla' => 'Hardware',
                'equipo' => 'Teclado',
                'prioridad' => 'Normal',
                'descripcion' => 'Algunas teclas del teclado dejaron de funcionar.',
                'afecta_otros' => false,
                'es_recurrente' => true,
                'comentarios' => null,
                'evidencia' => null,
                'informacion_adicional' => null,
            ],
            [
                'titulo' => 'Mouse no responde',
                'tipo_falla' => 'Hardware',
                'equipo' => 'Mouse',
                'prioridad' => 'Normal',
                'descripcion' => 'El mouse dejó de responder correctamente.',
                'afecta_otros' => false,
                'es_recurrente' => false,
                'comentarios' => null,
                'evidencia' => null,
                'informacion_adicional' => null,
            ],
            [
                'titulo' => 'Problema con correo electrónico',
                'tipo_falla' => 'Software',
                'equipo' => 'PC',
                'prioridad' => 'Alta',
                'descripcion' => 'No se pueden enviar ni recibir correos electrónicos.',
                'afecta_otros' => false,
                'es_recurrente' => false,
                'comentarios' => null,
                'evidencia' => null,
                'informacion_adicional' => null,
            ],
            [
                'titulo' => 'Aplicación no abre',
                'tipo_falla' => 'Software',
                'equipo' => 'PC',
                'prioridad' => 'Media',
                'descripcion' => 'La aplicación utilizada para el trabajo no inicia.',
                'afecta_otros' => false,
                'es_recurrente' => false,
                'comentarios' => null,
                'evidencia' => null,
                'informacion_adicional' => null,
            ],
            [
                'titulo' => 'Falla de conexión de red',
                'tipo_falla' => 'Red',
                'equipo' => 'PC',
                'prioridad' => 'Critica',
                'descripcion' => 'El equipo perdió completamente la conexión a la red.',
                'afecta_otros' => true,
                'es_recurrente' => true,
                'comentarios' => null,
                'evidencia' => null,
                'informacion_adicional' => null,
            ],
            [
                'titulo' => 'Computadora muy lenta',
                'tipo_falla' => 'Hardware',
                'equipo' => 'Laptop',
                'prioridad' => 'Media',
                'descripcion' => 'El equipo tarda demasiado en abrir programas y archivos.',
                'afecta_otros' => false,
                'es_recurrente' => true,
                'comentarios' => null,
                'evidencia' => null,
                'informacion_adicional' => null,
            ],
            [
                'titulo' => 'Problema con sistema operativo',
                'tipo_falla' => 'Software',
                'equipo' => 'PC',
                'prioridad' => 'Alta',
                'descripcion' => 'El sistema operativo presenta errores constantemente.',
                'afecta_otros' => false,
                'es_recurrente' => true,
                'comentarios' => null,
                'evidencia' => null,
                'informacion_adicional' => null,
            ],
            [
                'titulo' => 'No detecta unidad USB',
                'tipo_falla' => 'Hardware',
                'equipo' => 'PC',
                'prioridad' => 'Normal',
                'descripcion' => 'El equipo no reconoce las memorias USB conectadas.',
                'afecta_otros' => false,
                'es_recurrente' => false,
                'comentarios' => null,
                'evidencia' => null,
                'informacion_adicional' => null,
            ],
            [
                'titulo' => 'Pantalla parpadea',
                'tipo_falla' => 'Hardware',
                'equipo' => 'Monitor',
                'prioridad' => 'Alta',
                'descripcion' => 'La pantalla presenta parpadeos constantes.',
                'afecta_otros' => false,
                'es_recurrente' => true,
                'comentarios' => null,
                'evidencia' => null,
                'informacion_adicional' => null,
            ],
            [
                'titulo' => 'No funciona el audio',
                'tipo_falla' => 'Hardware',
                'equipo' => 'Laptop',
                'prioridad' => 'Normal',
                'descripcion' => 'El equipo dejó de reproducir sonido.',
                'afecta_otros' => false,
                'es_recurrente' => false,
                'comentarios' => null,
                'evidencia' => null,
                'informacion_adicional' => null,
            ],
            [
                'titulo' => 'VPN no conecta',
                'tipo_falla' => 'Red',
                'equipo' => 'Laptop',
                'prioridad' => 'Alta',
                'descripcion' => 'No es posible establecer conexión mediante VPN.',
                'afecta_otros' => false,
                'es_recurrente' => true,
                'comentarios' => null,
                'evidencia' => null,
                'informacion_adicional' => null,
            ],
            [
                'titulo' => 'Problema con Excel',
                'tipo_falla' => 'Software',
                'equipo' => 'PC',
                'prioridad' => 'Media',
                'descripcion' => 'Excel se cierra inesperadamente al abrir ciertos archivos.',
                'afecta_otros' => false,
                'es_recurrente' => true,
                'comentarios' => null,
                'evidencia' => null,
                'informacion_adicional' => null,
            ],
            [
                'titulo' => 'Cable de red dañado',
                'tipo_falla' => 'Red',
                'equipo' => 'PC',
                'prioridad' => 'Normal',
                'descripcion' => 'El cable de red presenta daños y la conexión es intermitente.',
                'afecta_otros' => false,
                'es_recurrente' => false,
                'comentarios' => null,
                'evidencia' => null,
                'informacion_adicional' => null,
            ],
            [
                'titulo' => 'Equipo se reinicia solo',
                'tipo_falla' => 'Hardware',
                'equipo' => 'PC',
                'prioridad' => 'Critica',
                'descripcion' => 'La computadora se reinicia automáticamente durante el trabajo.',
                'afecta_otros' => false,
                'es_recurrente' => true,
                'comentarios' => null,
                'evidencia' => null,
                'informacion_adicional' => null,
            ],
            [
                'titulo' => 'Acceso a sistema bloqueado',
                'tipo_falla' => 'Software',
                'equipo' => 'PC',
                'prioridad' => 'Alta',
                'descripcion' => 'El usuario no puede acceder a uno de los sistemas utilizados para trabajar.',
                'afecta_otros' => false,
                'es_recurrente' => false,
                'comentarios' => null,
                'evidencia' => null,
                'informacion_adicional' => null,
            ],
        ];

        foreach ($tickets as $index => $ticket) {

            // Repartir los tickets entre los usuarios permitidos
            $usuario = $usuarios[$index % $usuarios->count()];

            TicketU::create([
                'folio' => 'TKT-2026-' . str_pad($index + 1, 5, '0', STR_PAD_LEFT),
                'user_id' => $usuario->id,
                'titulo' => $ticket['titulo'],
                'tipo_falla' => $ticket['tipo_falla'],
                'equipo' => $ticket['equipo'],
                'prioridad' => $ticket['prioridad'],
                'descripcion' => $ticket['descripcion'],
                'afecta_otros' => $ticket['afecta_otros'],
                'es_recurrente' => $ticket['es_recurrente'],
                'comentarios' => $ticket['comentarios'],
                'evidencia' => $ticket['evidencia'],
                'estado' => 'pendiente',
                'informacion_adicional' => $ticket['informacion_adicional'],
            ]);
        }

        $this->command->info('20 tickets creados correctamente.');
    }
}