<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $usuarios = [
            [
                'login' => 'jhinojosa',
                'pswd' => Hash::make('12345678'),
                'name' => 'Jesus Hinojosa',
                'email' => 'jehg13072002@gmail.com',
                'active' => 'Y',
                'activation_code' => null,
                'priv_admin' => 'Y',
                'mfa' => null,
                'picture' => null,
                'role' => 'tecnologias',
                'phone' => null,
                'pswd_last_updated' => now(),
                'mfa_last_updated' => null,
            ],

            [
                'login' => 'jperez',
                'pswd' => Hash::make('12345678'),
                'name' => 'Juan Perez',
                'email' => 'juan.perez@gmail.com',
                'active' => 'Y',
                'activation_code' => null,
                'priv_admin' => 'N',
                'mfa' => null,
                'picture' => null,
                'role' => 'usuario',
                'phone' => null,
                'pswd_last_updated' => now(),
                'mfa_last_updated' => null,
            ],

            [
                'login' => 'cmartinez',
                'pswd' => Hash::make('12345678'),
                'name' => 'Carlos Martinez',
                'email' => 'carlos.martinez@gmail.com',
                'active' => 'Y',
                'activation_code' => null,
                'priv_admin' => 'N',
                'mfa' => null,
                'picture' => null,
                'role' => 'usuario',
                'phone' => null,
                'pswd_last_updated' => now(),
                'mfa_last_updated' => null,
            ],

            [
                'login' => 'agarcia',
                'pswd' => Hash::make('12345678'),
                'name' => 'Ana Garcia',
                'email' => 'ana.garcia@gmail.com',
                'active' => 'Y',
                'activation_code' => null,
                'priv_admin' => 'N',
                'mfa' => null,
                'picture' => null,
                'role' => 'usuario',
                'phone' => null,
                'pswd_last_updated' => now(),
                'mfa_last_updated' => null,
            ],

            [
                'login' => 'lrodriguez',
                'pswd' => Hash::make('12345678'),
                'name' => 'Luis Rodriguez',
                'email' => 'luis.rodriguez@gmail.com',
                'active' => 'Y',
                'activation_code' => null,
                'priv_admin' => 'N',
                'mfa' => null,
                'picture' => null,
                'role' => 'usuario',
                'phone' => null,
                'pswd_last_updated' => now(),
                'mfa_last_updated' => null,
            ],

            [
                'login' => 'mgonzalez',
                'pswd' => Hash::make('12345678'),
                'name' => 'Maria Gonzalez',
                'email' => 'maria.gonzalez@gmail.com',
                'active' => 'Y',
                'activation_code' => null,
                'priv_admin' => 'N',
                'mfa' => null,
                'picture' => null,
                'role' => 'usuario',
                'phone' => null,
                'pswd_last_updated' => now(),
                'mfa_last_updated' => null,
            ],

            [
                'login' => 'psanchez',
                'pswd' => Hash::make('12345678'),
                'name' => 'Pedro Sanchez',
                'email' => 'pedro.sanchez@gmail.com',
                'active' => 'Y',
                'activation_code' => null,
                'priv_admin' => 'N',
                'mfa' => null,
                'picture' => null,
                'role' => 'usuario',
                'phone' => null,
                'pswd_last_updated' => now(),
                'mfa_last_updated' => null,
            ],

            [
                'login' => 'storres',
                'pswd' => Hash::make('12345678'),
                'name' => 'Sofia Torres',
                'email' => 'sofia.torres@gmail.com',
                'active' => 'Y',
                'activation_code' => null,
                'priv_admin' => 'N',
                'mfa' => null,
                'picture' => null,
                'role' => 'usuario',
                'phone' => null,
                'pswd_last_updated' => now(),
                'mfa_last_updated' => null,
            ],

            [
                'login' => 'mramirez',
                'pswd' => Hash::make('12345678'),
                'name' => 'Miguel Ramirez',
                'email' => 'miguel.ramirez@gmail.com',
                'active' => 'Y',
                'activation_code' => null,
                'priv_admin' => 'N',
                'mfa' => null,
                'picture' => null,
                'role' => 'usuario',
                'phone' => null,
                'pswd_last_updated' => now(),
                'mfa_last_updated' => null,
            ],

            [
                'login' => 'lhernandez',
                'pswd' => Hash::make('12345678'),
                'name' => 'Laura Hernandez',
                'email' => 'laura.hernandez@gmail.com',
                'active' => 'Y',
                'activation_code' => null,
                'priv_admin' => 'N',
                'mfa' => null,
                'picture' => null,
                'role' => 'usuario',
                'phone' => null,
                'pswd_last_updated' => now(),
                'mfa_last_updated' => null,
            ],

            [
                'login' => 'dflores',
                'pswd' => Hash::make('12345678'),
                'name' => 'Diego Flores',
                'email' => 'diego.flores@gmail.com',
                'active' => 'Y',
                'activation_code' => null,
                'priv_admin' => 'N',
                'mfa' => null,
                'picture' => null,
                'role' => 'usuario',
                'phone' => null,
                'pswd_last_updated' => now(),
                'mfa_last_updated' => null,
            ],

            [
                'login' => 'vcruz',
                'pswd' => Hash::make('12345678'),
                'name' => 'Valeria Cruz',
                'email' => 'valeria.cruz@gmail.com',
                'active' => 'Y',
                'activation_code' => null,
                'priv_admin' => 'N',
                'mfa' => null,
                'picture' => null,
                'role' => 'usuario',
                'phone' => null,
                'pswd_last_updated' => now(),
                'mfa_last_updated' => null,
            ],

            [
                'login' => 'rmorales',
                'pswd' => Hash::make('12345678'),
                'name' => 'Roberto Morales',
                'email' => 'roberto.morales@gmail.com',
                'active' => 'Y',
                'activation_code' => null,
                'priv_admin' => 'N',
                'mfa' => null,
                'picture' => null,
                'role' => 'usuario',
                'phone' => null,
                'pswd_last_updated' => now(),
                'mfa_last_updated' => null,
            ],

            [
                'login' => 'fcastillo',
                'pswd' => Hash::make('12345678'),
                'name' => 'Fernanda Castillo',
                'email' => 'fernanda.castillo@gmail.com',
                'active' => 'Y',
                'activation_code' => null,
                'priv_admin' => 'N',
                'mfa' => null,
                'picture' => null,
                'role' => 'usuario',
                'phone' => null,
                'pswd_last_updated' => now(),
                'mfa_last_updated' => null,
            ],

            [
                'login' => 'avargas',
                'pswd' => Hash::make('12345678'),
                'name' => 'Alejandro Vargas',
                'email' => 'alejandro.vargas@gmail.com',
                'active' => 'Y',
                'activation_code' => null,
                'priv_admin' => 'N',
                'mfa' => null,
                'picture' => null,
                'role' => 'usuario',
                'phone' => null,
                'pswd_last_updated' => now(),
                'mfa_last_updated' => null,
            ],

            [
                'login' => 'gmendoza',
                'pswd' => Hash::make('12345678'),
                'name' => 'Gabriela Mendoza',
                'email' => 'gabriela.mendoza@gmail.com',
                'active' => 'Y',
                'activation_code' => null,
                'priv_admin' => 'N',
                'mfa' => null,
                'picture' => null,
                'role' => 'usuario',
                'phone' => null,
                'pswd_last_updated' => now(),
                'mfa_last_updated' => null,
            ],

            [
                'login' => 'rortega',
                'pswd' => Hash::make('12345678'),
                'name' => 'Ricardo Ortega',
                'email' => 'ricardo.ortega@gmail.com',
                'active' => 'Y',
                'activation_code' => null,
                'priv_admin' => 'N',
                'mfa' => null,
                'picture' => null,
                'role' => 'usuario',
                'phone' => null,
                'pswd_last_updated' => now(),
                'mfa_last_updated' => null,
            ],

            [
                'login' => 'dsilva',
                'pswd' => Hash::make('12345678'),
                'name' => 'Daniela Silva',
                'email' => 'daniela.silva@gmail.com',
                'active' => 'Y',
                'activation_code' => null,
                'priv_admin' => 'N',
                'mfa' => null,
                'picture' => null,
                'role' => 'usuario',
                'phone' => null,
                'pswd_last_updated' => now(),
                'mfa_last_updated' => null,
            ],

            [
                'login' => 'freyes',
                'pswd' => Hash::make('12345678'),
                'name' => 'Fernando Reyes',
                'email' => 'fernando.reyes@gmail.com',
                'active' => 'Y',
                'activation_code' => null,
                'priv_admin' => 'N',
                'mfa' => null,
                'picture' => null,
                'role' => 'usuario',
                'phone' => null,
                'pswd_last_updated' => now(),
                'mfa_last_updated' => null,
            ],

            [
                'login' => 'anavarro',
                'pswd' => Hash::make('12345678'),
                'name' => 'Andrea Navarro',
                'email' => 'andrea.navarro@gmail.com',
                'active' => 'Y',
                'activation_code' => null,
                'priv_admin' => 'N',
                'mfa' => null,
                'picture' => null,
                'role' => 'usuario',
                'phone' => null,
                'pswd_last_updated' => now(),
                'mfa_last_updated' => null,
            ],
        ];

        foreach ($usuarios as $usuario) {
            User::create($usuario);
        }
    }
}